### ISSUE TITLE
When used with Ember.js the 'Uncaught Office Web Extension script library file name should be office.js or office.debug.js' occurs

### ISSUE THREAD

**Issue by temecom** [andrewconnell/bower-MicrosoftOfficeJs#10]
- Standard app import is used
  - app.import('bower_components/microsoft-office-js/scripts/office/1/office.debug.js');
  - script loads but throws: 
    - UnrecognizedURLError: /assets/bower_components/microsoft-office-js/scripts/office/1/office.debug.js
- 'bower install' does not work when bower.json is updated with: "microsoft-office-js": "*",
  - ENOTFOUND Package microsoft-office-js not found
- 'bower install' creates the microsoft.office.js folder when bower.json if updated with:  "microsoft.office.js": "*"

Neither approach works.

**Comment by andrewconnell** [comment]
Microsoft as moved to a model where they don't publish the JS files even via NuGet anymore, rather the JS libraries are all hosted. Thus... keeping this project updated with the latest is not relevant anymore.
