### ISSUE TITLE
Bower install shows invalid-meta: description too long

### ISSUE THREAD

**Issue by divisha-emc** [andrewconnell/bower-MicrosoftOfficeJs#11]
Hi Team,

I am trying to do a bower install for microsoft.office.js. I am able to install it successfully. But there is a log reported saying:
**invalid-meta The description is too long, the limit is 140 characters.**
This is because the description added in your bower.json is about 199 characters and the preferred limit is 140 characters.

I am aware that this does not impact the working in any way the api works as expected but I am trying to reduce the warnings that we get during bower install.

Could you please reduce the length of the description to 140 characters?

Waiting to hear from you.

Regards,
Divisha

**Comment by andrewconnell** [comment]
Microsoft as moved to a model where they don't publish the JS files even via NuGet anymore, rather the JS libraries are all hosted. Thus... keeping this project updated with the latest is not relevant anymore.
