### ISSUE TITLE
Office Web Extension script library file name should be office.js or office.debug.js.

### ISSUE THREAD

**Issue by StfBauer** [andrewconnell/bower-MicrosoftOfficeJs#5]
Currently playing with office generator and it seems like I get this error when I launch and run the app.
After changing the reference in the mail section of bower.js from office.js to office.debug.js the message is gone.

@andrewconnell I can fix this and send you a PR if you like.

**Comment by andrewconnell** [comment]
My point in creating this library was to expose the exact same stuff that MSFT includes within the NuGet package that is used in Visual Studio based projects. Do those have the same issue? I don’t think it’s wise for this package to deviate from what is in NuGet.

FWIW, MSFT pushes hard on using their CDN references rather than locally hosted ones.

**Comment by StfBauer** [comment]
:+1: Got you.

I do some additional testing might find the problem / solution / cause of this issue. Theoretically it should happen have the same problem on CND too.

**Comment by andrewconnell** [comment]
Agreed… sounds like a good course of action.

**Comment by StfBauer** [comment]
OK found the problem. It is caused by the name of the base folder of the bower component. This contains office.js which causes this issue in the script.

You will find the problem on line 278 of office.debug.js. 
On this line the script try to find the base folder of the files 'office.js' or 'office.debug.js':

`indexOfJS = scriptSrcLowerCase.indexOf(scriptNameToCheck);`

scriptNameToCheck is assigned to an array of both files 'office.js' or 'office.debug.js'. 
scriptSrcLowerCase is assigned to '/bower_components/microsoft.office.js/scripts/office/1/office.js' in my case.

This indexOf should return first occurrence of 'office.js' or 'office.debug.js' which is include earlier in the bower component script path but not at the end.

It will return this 'office.js' (bold text)
    /bower_components/microsoft.**office.js**/scripts/office/1/office.js
instead the 'office.js' occurrence at the end (bold text)
    /bower_components/microsoft.office.js/scripts/office/1/**office.js**

on line 279 the script try to evaluate the base folder where all the other javascript files are stored and returns this folder. This should be **/bower_components/microsoft.office.js/scripts/office/1/**

Anyway this check fails and cause a couple of lines later the error message on the console.

**Solution:**
The part microsoft.office.js of the path needs to be rename to something like microsoft_office_js or microsoft.officejs after that all should work fine.

Hope this explanation was somehow logical ;)

**Comment by andrewconnell** [comment]
So is that renaming the path, or renaming the bower module? I think it’s the latter… because that’s what dictates the folder name right? Not sure if the bower.json syntax facilitates doing this another way…

**Comment by StfBauer** [comment]
The name of the folder is defined by the 'name' property inside the bower.json file. The good news is that we can change this independantly from the actual bower package registration name.

This means the package can still be listed as 'Microsoft.Office.js' but will be downloaded to a folder named 'microsoft-office-js'.

I tested it and it worked without any problem. I registered my fork of your repo on bower as 'temp-office-js' and renamed it inside bower.js. Now when I run 

`bower install temp-officers`

it creates a folder inside the bower components named 'microsoft-office-js'.

I think this is the best way to go because the current package is currently wired up with the 'yo office generators'. I think it is the last piece to change to have a solid fundament to implement wiredep and inject in the office generator. Last time i was unable to get the application running because of this issue.

**Comment by andrewconnell** [comment]
Cool! Do you want to submit PR? You should get credit for the fix :) I’d rec also logging an issue as well.

**Comment by StfBauer** [comment]
Sure I'll send you the PR. Should I increase the version number in bower.json or will you do?

**Comment by andrewconnell** [comment]
Feel free todo both… and make sure you are listed as a contrib!

**Comment by StfBauer** [comment]
Sure. Update version number and send PR.
