### ISSUE TITLE
File /bower_components/microsoft-office-js/scripts/office/1/outlook-15.03.js doesn't exists

### ISSUE THREAD

**Issue by HamletHakobyan** [andrewconnell/bower-MicrosoftOfficeJs#9]
The file _/bower_components/microsoft-office-js/scripts/office/1/outlook-15.03.js_ doesn't exists although the file _/bower_components/microsoft-office-js/scripts/office/1/o15apptofilemappingtable.js_ refers to it. Same for debug version.

**Comment by andrewconnell** [comment]
Good catch… submit a PR?

**Comment by HamletHakobyan** [comment]
Hi @andrewconnell . What do you mean? I haven't solution. I don't know should o15apptofilemappingtable.js refers to it or not.

**Comment by andrewconnell** [comment]
Microsoft as moved to a model where they don't publish the JS files even via NuGet anymore, rather the JS libraries are all hosted. Thus... keeping this project updated with the latest is not relevant anymore.
